### ISSUE TITLE
NetBoot Service stopps

### ISSUE THREAD

**Issue by davidschoefberger** [jamf/NetSUS#110]
Hi,
I have installed the NetSUS on 2 Ubuntu 16.04 VMs in different networks. Everything works fine for a few hours. Then the NetBoot Service stopps and I have to enable it again? Do you have any idea? I can't find any error in the logs.

**Comment by duncan-mccracken** [comment]
Hi David, I'm not entirely sure what would case the service to randomly stop, the DHCP engine has a fairly blunt configuration.
However, the next version (5.0) pending release has a completely new mechanism for providing the NetBoot service (BSDP instead of DHCP).
I'm currently updating the documentation at the moment, hoping to have it available for download in the next 48 hrs.

**Comment by davidschoefberger** [comment]
Hi @duncan-mccracken, thank you for that really fast reply. That sounds awesome!

**Comment by duncan-mccracken** [comment]
I'm quite literally updating the docs at the moment.
If you want to check out the new version (and changing docs) you can have a look at our development fork:
https://github.com/mondada/NetSUS

**Comment by davidschoefberger** [comment]
@duncan-mccracken I have installed the new version last week and I just checked the status. Its still running. Thanks! :)

**Comment by duncan-mccracken** [comment]
No problem, I hope you're enjoying the new version!
