### ISSUE TITLE
LDAP Broken After 4.2.1 Upgrade to 5.0

### ISSUE THREAD

**Issue by kendalljjohnson** [jamf/NetSUS#120]
LDAP login was working fine with 4.2.1 and now does not work for 5.0.

I have the same AD settings (also removed and re-added) and created the same group (also tried new groups) and I get "access denied". I can verify that our AD is seeing the connection and accepts the correct username password, but the permissions are not passed back to NetSUS. I worked with Jamf Support and they setup their own test instance and saw similar results.

Error in `/var/log/apache2/error.log`:

```[Thu Nov 15 10:30:44.078532 2018] [:error] [pid 1683] [client <myip>] PHP Notice:  Use of undefined constant LDAP_OPT_DIAGNOSTIC_MESSAGE - assumed 'LDAP_OPT_DIAGNOSTIC_MESSAGE' in /var/www/html/webadmin/index.php on line 39, referer: https://<myserver>/webadmin/
[Thu Nov 15 10:30:44.293692 2018] [:error] [pid 1683] [client <myip>] PHP Notice:  Undefined offset: 0 in /var/www/html/webadmin/index.php on line 77, referer: https://<myserver>/webadmin/
[Thu Nov 15 10:30:44.293719 2018] [:error] [pid 1683] [client <myip>] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/webadmin/index.php on line 77, referer: https://<myserver>/webadmin/```

**Comment by jelockwood** [comment]
@kendalljjohnson 
Whilst your and most other issues regarding LDAP are relating to AD use - not too surprising since the feature is currently _specifically_ for AD connectivity you might want to look at a previous issue I raised here - https://github.com/jamf/NetSUS/issues/99

In it I suggest they switch to a module called adldap2 which as might be deduced from the letters ad supports Active Directory but I know from using it with another different open source PHP based project that it also supports various LDAP i.e. non-AD servers.

If the author switched to this module I suspect not only would AD support be improved but it would also solve my problem of needing LDAP support.

ADLDAP2 has a feature which includes specifying various LDAP schemas so as to be able to correctly support different LDAP servers.

**Comment by kendalljjohnson** [comment]
@jelockwood After doing some troubleshooting with Duncan, we discovered it was a matter of my search base. If I put it at the base of my domain, not a specific OU where the groups lived, it worked no problem.

My apologies on not following up on closing this issue.
